config/routes.rb
Rails.application.routes.draw do
  resources :tweets, except: [:destroy]

  get '/cookies', to: 'cookies#index'
  get '/cookies/:name', to: 'cookies#name'

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: {maximum: 140}
  validates :content, exclusion: {in: ["dog"] }
  validate :content_doesnt_include_dog

  private

  def content_doesnt_include_dog
    if content.downcase.include?('dog')
      errors.add(:content, "cannot include the word dog")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_secure_password
  validates :username, presence: true, uniqueness: true, exclusion: {in: %w(ryanseacrest carsondaly)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?


  private

  def authenticate_user
    if !logged_in?
      flash[:notice] = 'You must be logged in to view this'
      redirect_to login_path
    end
  end

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController

  def index
  end

  def name
    cookies[:name] = params[:name]
    redirect_to '/cookies'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to tweets_path
    else
      flash[:notice] = 'Username or password was incorrect'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out!'
    redirect_to login_path
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :edit, :update]

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    # authenticate_user
    @tweet = Tweet.new
  end

  def create
    # authenticate_user
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      redirect_to tweet_path(@tweet)
    else
      render 'new'
    end
  end

  def edit
    # authenticate_user
    @tweet = Tweet.find(params[:id])
    unless @tweet.user == current_user
      redirect_to tweets_path and return
    end
  end

  def update
    # authenticate_user
    @tweet = Tweet.find(params[:id])
    unless @tweet.user == current_user
      redirect_to tweets_path and return
    end
    if @tweet.update(tweet_params)
      redirect_to tweet_path(@tweet)
    else
      render 'edit'
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:user_id, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_controller_helper.rb
module CookiesControllerHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/cookies/index.html.erb
<%= cookies[:name] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if logged_in? %>
        <li><%= current_user.username %></li>
        <li><%= link_to 'Tweet!', new_tweet_path %></li>
        <li><%= link_to 'Logout', logout_path %></li>
      <% else %>
        <li><%= link_to 'Login', login_path %></li>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<% if @tweet.errors.any? %>
  <% @tweet.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_for(@tweet) do |f| %>
  <!-- <label for="tweet_content">Content</label> -->
  <%= f.label :content %>

  <%= f.text_field :content, required: true %>
  <%= f.submit %>
<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Your Tweet!</h1>

<%= render 'form' %>

app/views/tweets/index.html.erb
<h1>Tweets Index!!</h1>

<ul>
  <% @tweets.each do |tweet| %>
    <li><%= link_to tweet.content, tweet %> was posted by <%= tweet.user.username %></li>
  <% end %>

  <%= link_to "All Tweets", tweets_path %>
</ul>

app/views/tweets/new.html.erb
<h1>Create a new Tweet!</h1>

<%= render 'form' %>

app/views/tweets/show.html.erb
<h1>One Tweet!</h1>

<%= flash[:notice] %>

<h2><%= @tweet.content %> by <%= @tweet.user.username %></h2>

<% if @tweet.user_id == current_user.id %>
  <%= link_to "Edit This Tweet", edit_tweet_path(@tweet) %>
<% end %>